#!/usr/bin/with-contenv bash

mkdir -p /opt/dnscrypt-proxy/share/dnscrypt-proxy/
cd /opt/dnscrypt-proxy/share/dnscrypt-proxy/
wget -O "dnscrypt-resolvers.csv" https://raw.githubusercontent.com/jedisct1/dnscrypt-resolvers/master/v1/dnscrypt-resolvers.csv
