#!/usr/bin/with-contenv bash

[[ ! -d /config/.git ]] && (git clone https://github.com/rix1337/RSScrawler.git /config)

# opt out for autoupdates
[ "$NO_UPDATES" ] && exit 0

cd /config
git fetch --all
git reset --hard origin/master
git pull origin master
chown -R abc:abc /config/
chown -R abc:abc /jd2/folderwatch
